// Generates src/ui-assets.gen.ts: the built web UI (apps/web/dist), base64
// encoded into the Worker script. Without a build, it writes a placeholder,
// and the Worker serves the server's placeholder page. The output is
// gitignored.

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "../../../apps/web/dist");
const out = join(here, "../src/ui-assets.gen.ts");

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });

const header = "// Generated by scripts/embed-ui.mjs. Do not edit.\n";
if (!existsSync(join(dist, "index.html"))) {
  writeFileSync(out, `${header}export const uiFiles: Record<string, string> = {};\n`);
  process.stdout.write("No apps/web/dist; the Worker will serve a placeholder page.\n");
} else {
  const files = walk(dist);
  const entries = files.map(
    (f) =>
      `  ${JSON.stringify(`/${relative(dist, f).split("\\").join("/")}`)}: ${JSON.stringify(readFileSync(f).toString("base64"))},`,
  );
  writeFileSync(
    out,
    `${header}export const uiFiles: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
  );
  process.stdout.write(`Embedded ${files.length} UI files.\n`);
}
