// Builds the npm package (dist/npm): the CLI bundled for Node, so
// `npx -y titlesearch mcp` works where MCP clients run Node. Our own
// workspace code is bundled; third-party packages stay external, as
// dependencies at the exact versions the workspace uses. `serve` needs Bun:
// use the release binary or desktop app for the web UI.

import { execFileSync } from "node:child_process";
import { chmodSync, cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../../..");
const out = join(here, "../dist/npm");
const json = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));
const cli = json("apps/cli/package.json");
const version = process.env.TITLESEARCH_VERSION ?? cli.version;

// Third-party dependencies of the CLI and every workspace package it reaches.
const deps = {};
const visit = (dir, seen = new Set()) => {
  if (seen.has(dir)) return;
  seen.add(dir);
  const pkg = json(`${dir}/package.json`);
  for (const [name, range] of Object.entries(pkg.dependencies ?? {})) {
    if (range.startsWith("workspace:"))
      visit(`packages/${name.replace("@titlesearch/", "")}`, seen);
    else deps[name] = range;
  }
};
visit("apps/cli");

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
// No UI in the npm package: `serve` runs from the binary.
writeFileSync(
  join(root, "apps/cli/src/ui-assets.gen.ts"),
  "// Generated by scripts/build-npm.mjs: no UI in the npm package.\nexport const uiAssets = undefined;\n",
);
execFileSync(
  "npx",
  [
    "--yes",
    "bun@1.4.2",
    "build",
    "apps/cli/src/main.ts",
    "--target=node",
    "--format=esm",
    // Splitting keeps Bun-only modules (bun:sqlite, the embedded-WASM loader)
    // in chunks that load only on Bun, behind their dynamic imports.
    "--splitting",
    "--entry-naming=titlesearch.mjs",
    "--chunk-naming=chunks/[name]-[hash].mjs",
    "--asset-naming=assets/[name]-[hash].[ext]",
    "--outdir",
    out,
    ...Object.keys(deps).flatMap((d) => ["--external", d, "--external", `${d}/*`]),
  ],
  { cwd: root, stdio: "inherit" },
);
// The bundle keeps the source's Bun shebang; npm users run it with Node.
const bundlePath = join(out, "titlesearch.mjs");
const bundle = readFileSync(bundlePath, "utf8").replace(/^#!.*\n/, "");
writeFileSync(bundlePath, `#!/usr/bin/env node\n${bundle}`);
chmodSync(bundlePath, 0o755);

const pkg = {
  name: "titlesearch",
  version,
  description: cli.description,
  license: "Apache-2.0",
  author: "ProdXP LLC",
  homepage: "https://github.com/prodxpdev/titlesearch",
  repository: { type: "git", url: "git+https://github.com/prodxpdev/titlesearch.git" },
  bugs: "https://github.com/prodxpdev/titlesearch/issues",
  keywords: ["mcp", "domains", "naming", "rdap", "availability"],
  // The MCP Registry checks this against server.json's name.
  mcpName: "io.github.prodxpdev/titlesearch",
  type: "module",
  bin: { titlesearch: "titlesearch.mjs" },
  files: ["titlesearch.mjs", "chunks", "assets", "README.md", "LICENSE", "NOTICE"],
  engines: { node: ">=22.13" },
  dependencies: Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b))),
};
writeFileSync(join(out, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);
for (const f of ["README.md", "LICENSE", "NOTICE"]) cpSync(join(root, f), join(out, f));
process.stdout.write(`Built the npm package titlesearch@${version} in ${out}\n`);
