// Generates src/ui-assets.gen.ts, which embeds the built web UI into the
// compiled binary with Bun file imports. Run before `bun build --compile`.
// With no apps/web/dist, it generates `uiAssets = undefined` and the server
// shows a placeholder page.

import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "../../web/dist");
const out = join(here, "../src/ui-assets.gen.ts");

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

if (!existsSync(join(dist, "index.html"))) {
  writeFileSync(
    out,
    "// Generated by scripts/embed-ui.mjs: no UI build found.\nexport const uiAssets = undefined;\n",
  );
  process.stdout.write("No apps/web/dist; the binary will serve a placeholder page.\n");
} else {
  const files = walk(dist);
  const lines = [
    "// Generated by scripts/embed-ui.mjs. Do not edit.",
    "// @ts-nocheck: Bun file imports of built assets; the types are in ui-assets.gen.d.ts.",
    'import { readFileSync } from "node:fs";',
    'import type { UiAssets } from "@titlesearch/server";',
    'import { contentTypeFor } from "./ui-assets.js";',
  ];
  const entries = files.map((f, i) => {
    const rel = relative(join(here, "../src"), f).split("\\").join("/");
    lines.push(`import f${i} from ${JSON.stringify(rel)} with { type: "file" };`);
    return `  [${JSON.stringify(`/${relative(dist, f).split("\\").join("/")}`)}, f${i}],`;
  });
  lines.push(
    "const paths = new Map<string, string>([",
    ...entries,
    "]);",
    "export const uiAssets: UiAssets = (path) => {",
    "  const file = paths.get(path);",
    "  return file ? { body: new Uint8Array(readFileSync(file)), contentType: contentTypeFor(path) } : undefined;",
    "};",
    "",
  );
  writeFileSync(out, lines.join("\n"));
  process.stdout.write(`Embedded ${files.length} UI files.\n`);
}
