// The MCP tool reference for the docs site, rendered from the same
// descriptions and Zod schemas the server registers, so it can't drift.
// docs/reference/mcp-tools.md is this output; a test checks it's current.

import * as z from "zod";
import {
  assessMarketConflictsDescription,
  CHECK_DOMAINS_DESCRIPTION,
  GENERATE_VARIANTS_DESCRIPTION,
  INSPECT_DOMAIN_DESCRIPTION,
  SUGGEST_NAMES_DESCRIPTION,
} from "./descriptions.js";
import {
  AssessMarketConflictsInput,
  CheckDomainsInput,
  GenerateVariantsInput,
  InspectDomainInput,
  SuggestNamesInput,
} from "./schemas.js";

interface ToolDoc {
  name: string;
  title: string;
  offered: string;
  description: string;
  input: z.ZodRawShape;
}

const TOOLS: ToolDoc[] = [
  {
    name: "check_domains",
    title: "Check domains",
    offered: "Always.",
    description: CHECK_DOMAINS_DESCRIPTION,
    input: CheckDomainsInput,
  },
  {
    name: "generate_variants",
    title: "Generate variants",
    offered: "Always. Makes no network requests.",
    description: GENERATE_VARIANTS_DESCRIPTION,
    input: GenerateVariantsInput,
  },
  {
    name: "suggest_names",
    title: "Suggest names",
    offered:
      "When the server has a model (an Anthropic API key). Otherwise the client model suggests names itself.",
    description: SUGGEST_NAMES_DESCRIPTION,
    input: SuggestNamesInput,
  },
  {
    name: "inspect_domain",
    title: "Inspect domain",
    offered: "When the server can probe sites: every shipped build.",
    description: INSPECT_DOMAIN_DESCRIPTION,
    input: InspectDomainInput,
  },
  {
    name: "assess_market_conflicts",
    title: "Assess market conflicts",
    offered:
      'When the server can probe sites. This is the description in "client" mode, where Claude judges; with a server-side model it says the server judges.',
    description: assessMarketConflictsDescription("client"),
    input: AssessMarketConflictsInput,
  },
];

interface JsonProp {
  type?: string | string[];
  description?: string;
  items?: { type?: string; enum?: string[] };
  enum?: string[];
  minItems?: number;
  maxItems?: number;
  minimum?: number;
  maximum?: number;
  maxLength?: number;
}

function typeOf(p: JsonProp): string {
  if (p.enum) return p.enum.map((e) => `"${e}"`).join(" \\| ");
  if (p.type === "array") {
    const item = p.items?.enum
      ? `(${p.items.enum.map((e) => `"${e}"`).join(" \\| ")})`
      : (p.items?.type ?? "any");
    return `${item}[]`;
  }
  return Array.isArray(p.type) ? p.type.join(" \\| ") : (p.type ?? "any");
}

function limits(p: JsonProp): string {
  const parts: string[] = [];
  const items = (n: number) => `${n} item${n === 1 ? "" : "s"}`;
  if (p.minItems !== undefined && p.maxItems !== undefined)
    parts.push(
      p.minItems === 0 ? `at most ${items(p.maxItems)}` : `${p.minItems} to ${items(p.maxItems)}`,
    );
  else if (p.minItems !== undefined) parts.push(`at least ${items(p.minItems)}`);
  else if (p.maxItems !== undefined) parts.push(`at most ${items(p.maxItems)}`);
  if (p.minimum !== undefined || p.maximum !== undefined)
    parts.push(`${p.minimum ?? ""} to ${p.maximum ?? ""}`.trim());
  if (p.maxLength !== undefined) parts.push(`at most ${p.maxLength} characters`);
  return parts.join("; ");
}

const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n+/g, " ");

export function renderToolReference(): string {
  const out = [
    "# MCP tools",
    "",
    "<!-- Generated by packages/mcp/src/reference.ts. Edit the descriptions and schemas there, then run `pnpm --filter @titlesearch/mcp docs`. -->",
    "",
    "Every tool is read-only (`readOnlyHint: true`, `destructiveHint: false`) and open-world. A call takes at most 20 names and 50 domains. Titlesearch isn't a trademark search. The server also offers a `saas_naming_session` prompt with `product` and `audience` arguments.",
    "",
  ];
  for (const t of TOOLS) {
    const schema = z.toJSONSchema(z.object(t.input)) as {
      properties: Record<string, JsonProp>;
      required?: string[];
    };
    out.push(
      `## \`${t.name}\``,
      "",
      `**${t.title}.** Offered: ${t.offered}`,
      "",
      t.description,
      "",
    );
    out.push("| Input | Type | Required | Limits | Meaning |", "|---|---|---|---|---|");
    for (const [name, p] of Object.entries(schema.properties)) {
      out.push(
        `| \`${name}\` | ${typeOf(p)} | ${schema.required?.includes(name) ? "Yes" : "No"} | ${cell(limits(p))} | ${cell(p.description ?? "")} |`,
      );
    }
    out.push("");
  }
  return `${out.join("\n").trimEnd()}\n`;
}
